# Generated by Django 5.1 on 2024-08-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
