# Generated by Django 5.1 on 2024-08-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='alumni_blog_news/media/blog_images/Indian_Institute_of_Technology,_Indore_Logo.png', upload_to='blog_images/'),
        ),
    ]
