# Generated by Django 5.1 on 2024-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_image_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='media/news_images/Indian_Institute_of_Technology,_Indore_Logo.png', upload_to='news_images/'),
        ),
    ]
